/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4Frames;

/**
 *
 * @author Aluminium
 */
public class boardPanel extends javax.swing.JFrame {

    /**
     * Creates new form boardPanel
     */
    public boardPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel JBoardPanel = new javax.swing.JPanel();
        jBoardTitlePanel = new javax.swing.JPanel();
        jBoardLabel = new javax.swing.JLabel();
        jBoardTextField = new javax.swing.JTextField();
        jButton2BoardColumn = new javax.swing.JButton();
        jButton3BoardColumn = new javax.swing.JButton();
        jButton4BoardColumn = new javax.swing.JButton();
        jButton5BoardColumn = new javax.swing.JButton();
        jButton6BoardColumn = new javax.swing.JButton();
        jButton1BoardColumn = new javax.swing.JButton();
        jButton7BoardColumn = new javax.swing.JButton();
        jLabelBoardColumns = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBoardLabel.setFont(new java.awt.Font("Futura", 0, 50)); // NOI18N
        jBoardLabel.setForeground(new java.awt.Color(204, 102, 0));
        jBoardLabel.setText("Connect 4");

        org.jdesktop.layout.GroupLayout jBoardTitlePanelLayout = new org.jdesktop.layout.GroupLayout(jBoardTitlePanel);
        jBoardTitlePanel.setLayout(jBoardTitlePanelLayout);
        jBoardTitlePanelLayout.setHorizontalGroup(
            jBoardTitlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jBoardTitlePanelLayout.createSequentialGroup()
                .add(jBoardTitlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jBoardTitlePanelLayout.createSequentialGroup()
                        .add(113, 113, 113)
                        .add(jBoardTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 485, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jBoardTitlePanelLayout.createSequentialGroup()
                        .add(245, 245, 245)
                        .add(jBoardLabel)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jBoardTitlePanelLayout.setVerticalGroup(
            jBoardTitlePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jBoardTitlePanelLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jBoardLabel)
                .add(18, 18, 18)
                .add(jBoardTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2BoardColumn.setText("2");

        jButton3BoardColumn.setText("3");

        jButton4BoardColumn.setText("4");

        jButton5BoardColumn.setText("5");

        jButton6BoardColumn.setText("6");

        jButton1BoardColumn.setText("1");

        jButton7BoardColumn.setText("7");
        jButton7BoardColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7BoardColumnActionPerformed(evt);
            }
        });

        jLabelBoardColumns.setText("columns");

        org.jdesktop.layout.GroupLayout JBoardPanelLayout = new org.jdesktop.layout.GroupLayout(JBoardPanel);
        JBoardPanel.setLayout(JBoardPanelLayout);
        JBoardPanelLayout.setHorizontalGroup(
            JBoardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JBoardPanelLayout.createSequentialGroup()
                .add(116, 116, 116)
                .add(jButton1BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton6BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton7BoardColumn, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(51, 51, 51)
                .add(jLabelBoardColumns)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jBoardTitlePanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JBoardPanelLayout.setVerticalGroup(
            JBoardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JBoardPanelLayout.createSequentialGroup()
                .add(jBoardTitlePanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(JBoardPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.CENTER)
                    .add(jButton1BoardColumn)
                    .add(jButton7BoardColumn)
                    .add(jButton2BoardColumn)
                    .add(jButton3BoardColumn)
                    .add(jButton4BoardColumn)
                    .add(jButton5BoardColumn)
                    .add(jButton6BoardColumn)
                    .add(jLabelBoardColumns))
                .add(0, 60, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(JBoardPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(JBoardPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7BoardColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7BoardColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7BoardColumnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBoardLabel;
    private javax.swing.JTextField jBoardTextField;
    private javax.swing.JPanel jBoardTitlePanel;
    private javax.swing.JButton jButton1BoardColumn;
    private javax.swing.JButton jButton2BoardColumn;
    private javax.swing.JButton jButton3BoardColumn;
    private javax.swing.JButton jButton4BoardColumn;
    private javax.swing.JButton jButton5BoardColumn;
    private javax.swing.JButton jButton6BoardColumn;
    private javax.swing.JButton jButton7BoardColumn;
    private javax.swing.JLabel jLabelBoardColumns;
    // End of variables declaration//GEN-END:variables
}
