/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4Frames;

/**
 *
 * @author Aluminium
 */
public class EnterPlayerNames extends javax.swing.JFrame {

    /**
     * Creates new form EnterPlayerNames
     */
    public EnterPlayerNames() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpEnterbody = new javax.swing.JPanel();
        jpEnterTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpEnterPanel = new javax.swing.JPanel();
        jpEnterLabel2 = new javax.swing.JLabel();
        jpEnterLabel = new javax.swing.JLabel();
        jpEnterInput1 = new javax.swing.JTextField();
        jpEnterInput2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enter Player Names");

        jpEnterbody.setBackground(new java.awt.Color(153, 204, 255));
        jpEnterbody.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jpEnterTitle.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("Enter names of the players below:");

        org.jdesktop.layout.GroupLayout jpEnterTitleLayout = new org.jdesktop.layout.GroupLayout(jpEnterTitle);
        jpEnterTitle.setLayout(jpEnterTitleLayout);
        jpEnterTitleLayout.setHorizontalGroup(
            jpEnterTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpEnterTitleLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1)
                .add(67, 67, 67))
        );
        jpEnterTitleLayout.setVerticalGroup(
            jpEnterTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpEnterTitleLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .add(jLabel1)
                .addContainerGap())
        );

        jpEnterPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jpEnterLabel2.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jpEnterLabel2.setText("Player 1");

        jpEnterLabel.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        jpEnterLabel.setText("Player 2");

        jpEnterInput1.setBackground(new java.awt.Color(208, 226, 244));
        jpEnterInput1.setText("name");
        jpEnterInput1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpEnterInput1ActionPerformed(evt);
            }
        });

        jpEnterInput2.setBackground(new java.awt.Color(208, 228, 248));
        jpEnterInput2.setText("name");
        jpEnterInput2.setToolTipText("");

        org.jdesktop.layout.GroupLayout jpEnterPanelLayout = new org.jdesktop.layout.GroupLayout(jpEnterPanel);
        jpEnterPanel.setLayout(jpEnterPanelLayout);
        jpEnterPanelLayout.setHorizontalGroup(
            jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterPanelLayout.createSequentialGroup()
                .add(36, 36, 36)
                .add(jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jpEnterLabel2)
                    .add(jpEnterLabel))
                .add(65, 65, 65)
                .add(jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jpEnterInput1)
                    .add(jpEnterInput2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEnterPanelLayout.setVerticalGroup(
            jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterPanelLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jpEnterLabel2)
                    .add(jpEnterInput1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(30, 30, 30)
                .add(jpEnterPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jpEnterLabel)
                    .add(jpEnterInput2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jpEnterbodyLayout = new org.jdesktop.layout.GroupLayout(jpEnterbody);
        jpEnterbody.setLayout(jpEnterbodyLayout);
        jpEnterbodyLayout.setHorizontalGroup(
            jpEnterbodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterbodyLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jpEnterPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .add(jpEnterTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpEnterbodyLayout.setVerticalGroup(
            jpEnterbodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterbodyLayout.createSequentialGroup()
                .add(jpEnterTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(jpEnterPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 40, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterbody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpEnterbody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpEnterInput1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpEnterInput1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpEnterInput1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterPlayerNames.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterPlayerNames().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jpEnterInput1;
    private javax.swing.JTextField jpEnterInput2;
    private javax.swing.JLabel jpEnterLabel;
    private javax.swing.JLabel jpEnterLabel2;
    private javax.swing.JPanel jpEnterPanel;
    private javax.swing.JPanel jpEnterTitle;
    private javax.swing.JPanel jpEnterbody;
    // End of variables declaration//GEN-END:variables
}
