/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package connect4Frames;

/**
 *
 * @author Aluminium
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBody = new javax.swing.JPanel();
        jpTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpMenuItems = new javax.swing.JPanel();
        PlayButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpBody.setBackground(new java.awt.Color(153, 204, 255));
        jpBody.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 153, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 51, 102), new java.awt.Color(51, 0, 204)));

        jpTitle.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Futura", 0, 70)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 102, 0));
        jLabel1.setText("CONNECT 4");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 3, true));

        org.jdesktop.layout.GroupLayout jpTitleLayout = new org.jdesktop.layout.GroupLayout(jpTitle);
        jpTitle.setLayout(jpTitleLayout);
        jpTitleLayout.setHorizontalGroup(
            jpTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .add(jLabel1)
                .add(195, 195, 195))
        );
        jpTitleLayout.setVerticalGroup(
            jpTitleLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpTitleLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .add(jLabel1)
                .add(25, 25, 25))
        );

        jpMenuItems.setBackground(new java.awt.Color(153, 204, 255));

        PlayButton.setFont(new java.awt.Font("Futura", 0, 55)); // NOI18N
        PlayButton.setForeground(new java.awt.Color(204, 102, 0));
        PlayButton.setText("PLAY");

        helpButton.setFont(new java.awt.Font("Futura", 0, 55)); // NOI18N
        helpButton.setForeground(new java.awt.Color(204, 102, 0));
        helpButton.setText("HELP");

        org.jdesktop.layout.GroupLayout jpMenuItemsLayout = new org.jdesktop.layout.GroupLayout(jpMenuItems);
        jpMenuItems.setLayout(jpMenuItemsLayout);
        jpMenuItemsLayout.setHorizontalGroup(
            jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpMenuItemsLayout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .add(jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PlayButton)
                    .add(helpButton))
                .add(30, 30, 30))
        );
        jpMenuItemsLayout.setVerticalGroup(
            jpMenuItemsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpMenuItemsLayout.createSequentialGroup()
                .add(79, 79, 79)
                .add(PlayButton)
                .add(62, 62, 62)
                .add(helpButton)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jpBodyLayout = new org.jdesktop.layout.GroupLayout(jpBody);
        jpBody.setLayout(jpBodyLayout);
        jpBodyLayout.setHorizontalGroup(
            jpBodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jpBodyLayout.createSequentialGroup()
                .add(278, 278, 278)
                .add(jpMenuItems, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBodyLayout.setVerticalGroup(
            jpBodyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpBodyLayout.createSequentialGroup()
                .add(jpTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jpMenuItems, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpBody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpBody, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpBody.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton helpButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpBody;
    private javax.swing.JPanel jpMenuItems;
    private javax.swing.JPanel jpTitle;
    // End of variables declaration//GEN-END:variables
}
